<?php
declare(strict_types=1);
use Elogic\StoreLocator\Block\Index\Index;

/** @var Index $block */

?>


<div id="map" style="height: 50em; width: 100%;"></div>
<script>
    require(['jquery'], function($) {
        $('a.stretched-link').on('click', function () {
            var id = $(this).attr('id');
            $.ajax({
                url: 'https://flush795-magento/rest/V2/shop/getShopById/' + id,
                dataType: 'json'
            }).error(function(result) {
                console.log('error');
            }).success(function(result) {
                const position = { lat: result.latitude, lng: result.longitude };
                const map = new google.maps.Map(document.getElementById("map"), {
                    zoom: 20,
                    center: position,
                });
                const marker = new google.maps.Marker({
                    position: position,
                    map: map,
                });
                openMarkerDescription(result, marker);
            });
        });
    });

    function initMap() {
        require(['jquery'], function($) {
            $.ajax({
                url: 'https://flush795-magento/rest/V2/shop/getShopById/1',
                dataType: 'json'
            }).error(function (result) {
                console.log('error');
            }).success(function (result) {
                const position = {lat: result.latitude, lng: result.longitude};
                const map = new google.maps.Map(document.getElementById("map"), {
                    zoom: 20,
                    center: position,
                });
                const marker = new google.maps.Marker({
                    position: position,
                    map: map,
                });
                openMarkerDescription(result, marker);
            });
        });
    }

    function openMarkerDescription(result, marker) {
        var content = document.createElement('div');
        content.innerHTML = "" +
            "<h1><strong>" + result.shop_name + "</strong></h1>" +
            "<p>City: " + result.shop_city + "</p>" +
            "<p>ZIP: " + result.shop_zip + "</p>" +
            "<p>Address: " + result.shop_address + "</p>" +
            "<p>State: " + result.shop_state + "</p>" +
            "<p>Description: " + result.description + "</p>";
        var infowindow = new google.maps.InfoWindow({
            content: content
        });
        infowindow.open(map, marker);
        google.maps.event.addListener(marker, 'click', function() {
            infowindow.open(map, marker);
        });
    }
</script>
<script
    src="https://maps.googleapis.com/maps/api/js?key=<?= $block->getApiKey() ?>&callback=initMap&libraries=&v=weekly"
    async
></script>
